# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hmrf_build_neighbors_6n <- function(mask) {
    .Call(`_SEFT_hmrf_build_neighbors_6n`, mask)
}

hmrf_llr_mixnorm <- function(x_mask, p, mu, sig2, f0_absmax2 = FALSE, f1_absmax01 = FALSE) {
    .Call(`_SEFT_hmrf_llr_mixnorm`, x_mask, p, mu, sig2, f0_absmax2, f1_absmax01)
}

hmrf_gem_fit <- function(nb, x3d, L, iter_max, sweep_b, sweep_r, a, b, alpha, stpmax, max_backtrack, tol, beta_init, h_init, p_init, mu_init, sig2_init, init_prob_theta, seed, verbose = TRUE, f0_absmax2 = FALSE, f1_absmax01 = FALSE, fixing_beta = FALSE) {
    .Call(`_SEFT_hmrf_gem_fit`, nb, x3d, L, iter_max, sweep_b, sweep_r, a, b, alpha, stpmax, max_backtrack, tol, beta_init, h_init, p_init, mu_init, sig2_init, init_prob_theta, seed, verbose, f0_absmax2, f1_absmax01, fixing_beta)
}

hmrf_estimate_gamma_base <- function(nb, baseline3d, beta, h, p, mu, sig2, burnin, sweeps, thin, init_prob_theta, seed, n_chains = 4L, random_scan = TRUE, init_mode = 3L, f0_absmax2 = FALSE, f1_absmax01 = FALSE, clamp_eps = 1e-8) {
    .Call(`_SEFT_hmrf_estimate_gamma_base`, nb, baseline3d, beta, h, p, mu, sig2, burnin, sweeps, thin, init_prob_theta, seed, n_chains, random_scan, init_mode, f0_absmax2, f1_absmax01, clamp_eps)
}

hmrf_plis_reweight_absmax <- function(nb, candidate3d, baseline3d, gamma_base_in, p, mu, sig2, clamp_eps = 1e-10) {
    .Call(`_SEFT_hmrf_plis_reweight_absmax`, nb, candidate3d, baseline3d, gamma_base_in, p, mu, sig2, clamp_eps)
}

cal_CLAW_scores_3d <- function(T_data, T_data_til, P, P_til, lambda = 0.5, h = 2.5, bandwidth = 2.5, neighbor_range = 5L, c = 0.99) {
    .Call(`_SEFT_cal_CLAW_scores_3d`, T_data, T_data_til, P, P_til, lambda, h, bandwidth, neighbor_range, c)
}

Simes_PC_test_cpp <- function(p_values, u) {
    .Call(`_SEFT_Simes_PC_test_cpp`, p_values, u)
}

cal_ELIS_cpp <- function(log_PLIS_scores, u, method = "Sym_miny", alpha_k = 0.05, til_mth = "oneminus", signmin_flag = FALSE) {
    .Call(`_SEFT_cal_ELIS_cpp`, log_PLIS_scores, u, method, alpha_k, til_mth, signmin_flag)
}
