// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hmrf_build_neighbors_6n
List hmrf_build_neighbors_6n(LogicalVector mask);
RcppExport SEXP _SEFT_hmrf_build_neighbors_6n(SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(hmrf_build_neighbors_6n(mask));
    return rcpp_result_gen;
END_RCPP
}
// hmrf_llr_mixnorm
NumericVector hmrf_llr_mixnorm(NumericVector x_mask, NumericVector p, NumericVector mu, NumericVector sig2, bool f0_absmax2, bool f1_absmax01);
RcppExport SEXP _SEFT_hmrf_llr_mixnorm(SEXP x_maskSEXP, SEXP pSEXP, SEXP muSEXP, SEXP sig2SEXP, SEXP f0_absmax2SEXP, SEXP f1_absmax01SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mask(x_maskSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< bool >::type f0_absmax2(f0_absmax2SEXP);
    Rcpp::traits::input_parameter< bool >::type f1_absmax01(f1_absmax01SEXP);
    rcpp_result_gen = Rcpp::wrap(hmrf_llr_mixnorm(x_mask, p, mu, sig2, f0_absmax2, f1_absmax01));
    return rcpp_result_gen;
END_RCPP
}
// hmrf_gem_fit
List hmrf_gem_fit(List nb, NumericVector x3d, int L, int iter_max, int sweep_b, int sweep_r, double a, double b, double alpha, double stpmax, int max_backtrack, double tol, double beta_init, double h_init, NumericVector p_init, NumericVector mu_init, NumericVector sig2_init, double init_prob_theta, int seed, bool verbose, bool f0_absmax2, bool f1_absmax01, bool fixing_beta);
RcppExport SEXP _SEFT_hmrf_gem_fit(SEXP nbSEXP, SEXP x3dSEXP, SEXP LSEXP, SEXP iter_maxSEXP, SEXP sweep_bSEXP, SEXP sweep_rSEXP, SEXP aSEXP, SEXP bSEXP, SEXP alphaSEXP, SEXP stpmaxSEXP, SEXP max_backtrackSEXP, SEXP tolSEXP, SEXP beta_initSEXP, SEXP h_initSEXP, SEXP p_initSEXP, SEXP mu_initSEXP, SEXP sig2_initSEXP, SEXP init_prob_thetaSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP f0_absmax2SEXP, SEXP f1_absmax01SEXP, SEXP fixing_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x3d(x3dSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    Rcpp::traits::input_parameter< int >::type sweep_b(sweep_bSEXP);
    Rcpp::traits::input_parameter< int >::type sweep_r(sweep_rSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type stpmax(stpmaxSEXP);
    Rcpp::traits::input_parameter< int >::type max_backtrack(max_backtrackSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< double >::type h_init(h_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_init(p_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig2_init(sig2_initSEXP);
    Rcpp::traits::input_parameter< double >::type init_prob_theta(init_prob_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type f0_absmax2(f0_absmax2SEXP);
    Rcpp::traits::input_parameter< bool >::type f1_absmax01(f1_absmax01SEXP);
    Rcpp::traits::input_parameter< bool >::type fixing_beta(fixing_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(hmrf_gem_fit(nb, x3d, L, iter_max, sweep_b, sweep_r, a, b, alpha, stpmax, max_backtrack, tol, beta_init, h_init, p_init, mu_init, sig2_init, init_prob_theta, seed, verbose, f0_absmax2, f1_absmax01, fixing_beta));
    return rcpp_result_gen;
END_RCPP
}
// hmrf_estimate_gamma_base
List hmrf_estimate_gamma_base(List nb, NumericVector baseline3d, double beta, double h, NumericVector p, NumericVector mu, NumericVector sig2, int burnin, int sweeps, int thin, double init_prob_theta, int seed, int n_chains, bool random_scan, int init_mode, bool f0_absmax2, bool f1_absmax01, double clamp_eps);
RcppExport SEXP _SEFT_hmrf_estimate_gamma_base(SEXP nbSEXP, SEXP baseline3dSEXP, SEXP betaSEXP, SEXP hSEXP, SEXP pSEXP, SEXP muSEXP, SEXP sig2SEXP, SEXP burninSEXP, SEXP sweepsSEXP, SEXP thinSEXP, SEXP init_prob_thetaSEXP, SEXP seedSEXP, SEXP n_chainsSEXP, SEXP random_scanSEXP, SEXP init_modeSEXP, SEXP f0_absmax2SEXP, SEXP f1_absmax01SEXP, SEXP clamp_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baseline3d(baseline3dSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type sweeps(sweepsSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type init_prob_theta(init_prob_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_chains(n_chainsSEXP);
    Rcpp::traits::input_parameter< bool >::type random_scan(random_scanSEXP);
    Rcpp::traits::input_parameter< int >::type init_mode(init_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type f0_absmax2(f0_absmax2SEXP);
    Rcpp::traits::input_parameter< bool >::type f1_absmax01(f1_absmax01SEXP);
    Rcpp::traits::input_parameter< double >::type clamp_eps(clamp_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(hmrf_estimate_gamma_base(nb, baseline3d, beta, h, p, mu, sig2, burnin, sweeps, thin, init_prob_theta, seed, n_chains, random_scan, init_mode, f0_absmax2, f1_absmax01, clamp_eps));
    return rcpp_result_gen;
END_RCPP
}
// hmrf_plis_reweight_absmax
NumericVector hmrf_plis_reweight_absmax(List nb, NumericVector candidate3d, NumericVector baseline3d, NumericVector gamma_base_in, NumericVector p, NumericVector mu, NumericVector sig2, double clamp_eps);
RcppExport SEXP _SEFT_hmrf_plis_reweight_absmax(SEXP nbSEXP, SEXP candidate3dSEXP, SEXP baseline3dSEXP, SEXP gamma_base_inSEXP, SEXP pSEXP, SEXP muSEXP, SEXP sig2SEXP, SEXP clamp_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type candidate3d(candidate3dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baseline3d(baseline3dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_base_in(gamma_base_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< double >::type clamp_eps(clamp_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(hmrf_plis_reweight_absmax(nb, candidate3d, baseline3d, gamma_base_in, p, mu, sig2, clamp_eps));
    return rcpp_result_gen;
END_RCPP
}
// cal_CLAW_scores_3d
Rcpp::List cal_CLAW_scores_3d(arma::cube T_data, arma::cube T_data_til, arma::cube P, arma::cube P_til, double lambda, double h, double bandwidth, int neighbor_range, double c);
RcppExport SEXP _SEFT_cal_CLAW_scores_3d(SEXP T_dataSEXP, SEXP T_data_tilSEXP, SEXP PSEXP, SEXP P_tilSEXP, SEXP lambdaSEXP, SEXP hSEXP, SEXP bandwidthSEXP, SEXP neighbor_rangeSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type T_data(T_dataSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type T_data_til(T_data_tilSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type P_til(P_tilSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< int >::type neighbor_range(neighbor_rangeSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(cal_CLAW_scores_3d(T_data, T_data_til, P, P_til, lambda, h, bandwidth, neighbor_range, c));
    return rcpp_result_gen;
END_RCPP
}
// Simes_PC_test_cpp
double Simes_PC_test_cpp(arma::vec p_values, int u);
RcppExport SEXP _SEFT_Simes_PC_test_cpp(SEXP p_valuesSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type p_values(p_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(Simes_PC_test_cpp(p_values, u));
    return rcpp_result_gen;
END_RCPP
}
// cal_ELIS_cpp
double cal_ELIS_cpp(arma::mat log_PLIS_scores, int u, std::string method, double alpha_k, std::string til_mth, bool signmin_flag);
RcppExport SEXP _SEFT_cal_ELIS_cpp(SEXP log_PLIS_scoresSEXP, SEXP uSEXP, SEXP methodSEXP, SEXP alpha_kSEXP, SEXP til_mthSEXP, SEXP signmin_flagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type log_PLIS_scores(log_PLIS_scoresSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_k(alpha_kSEXP);
    Rcpp::traits::input_parameter< std::string >::type til_mth(til_mthSEXP);
    Rcpp::traits::input_parameter< bool >::type signmin_flag(signmin_flagSEXP);
    rcpp_result_gen = Rcpp::wrap(cal_ELIS_cpp(log_PLIS_scores, u, method, alpha_k, til_mth, signmin_flag));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SEFT_hmrf_build_neighbors_6n", (DL_FUNC) &_SEFT_hmrf_build_neighbors_6n, 1},
    {"_SEFT_hmrf_llr_mixnorm", (DL_FUNC) &_SEFT_hmrf_llr_mixnorm, 6},
    {"_SEFT_hmrf_gem_fit", (DL_FUNC) &_SEFT_hmrf_gem_fit, 23},
    {"_SEFT_hmrf_estimate_gamma_base", (DL_FUNC) &_SEFT_hmrf_estimate_gamma_base, 18},
    {"_SEFT_hmrf_plis_reweight_absmax", (DL_FUNC) &_SEFT_hmrf_plis_reweight_absmax, 8},
    {"_SEFT_cal_CLAW_scores_3d", (DL_FUNC) &_SEFT_cal_CLAW_scores_3d, 9},
    {"_SEFT_Simes_PC_test_cpp", (DL_FUNC) &_SEFT_Simes_PC_test_cpp, 2},
    {"_SEFT_cal_ELIS_cpp", (DL_FUNC) &_SEFT_cal_ELIS_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SEFT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
