test_that("optional setup and R backend use the same installed paths", {
    skip_on_os("windows")
    script <- system.file("optional", "setup_working_models.sh", package = "SEFT")
    expect_true(file.exists(script))
    expect_true(file.exists(system.file("NOTICE", package = "SEFT")))
    old <- Sys.getenv("SEFT_OPTIONAL_ROOT", unset = NA_character_)
    on.exit(if (is.na(old)) Sys.unsetenv("SEFT_OPTIONAL_ROOT") else Sys.setenv(SEFT_OPTIONAL_ROOT = old), add = TRUE)
    Sys.unsetenv("SEFT_OPTIONAL_ROOT")
    paths <- system2("bash", c(shQuote(script), "--check-paths"), stdout = TRUE, stderr = TRUE)
    expect_null(attr(paths, "status"))
    expect_identical(paths[[1L]], normalizePath(system.file(package = "SEFT"), winslash = "/"))
    expect_identical(paths[[2L]], SEFT:::.optional_root())
    expect_true(file.exists(file.path(paths[[1L]], "optional", "src", "absmax_backend.cpp")))
    configured <- tempfile("seft-working-models-")
    Sys.setenv(SEFT_OPTIONAL_ROOT = configured)
    configured_paths <- system2("bash", c(shQuote(script), "--check-paths"), stdout = TRUE, stderr = TRUE)
    expect_identical(configured_paths[[2L]], SEFT:::.optional_root())
})
